// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var expressions, notReserved;
  notReserved = require('../combinators').notReserved;
  module.exports = expressions = [];
  expressions.push(require('../nodes/ArrayExpression'));
  expressions.push(require('../nodes/AssignmentExpression'));
  expressions.push(require('../nodes/CallExpression'));
  expressions.push(require('../nodes/FunctionExpression'));
  expressions.push(function () {
    return notReserved(require('../nodes/Identifier'));
  });
  expressions.push(require('../nodes/Literal'));
  expressions.push(require('../nodes/NewExpression'));
  expressions.push(require('../nodes/ThisExpression'));
}.call(this);
