// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var expressions, Literal, oneOf;
  Literal = require('./Literal');
  oneOf = require('../combinators').oneOf;
  expressions = [Literal];
  module.exports = function (depth) {
    var cache$;
    if (!(depth > 0))
      return Literal(0);
    return (cache$ = oneOf(expressions)).apply(cache$, [].slice.call(arguments).concat());
  };
  expressions.push(require('../nodes/ArrayExpression'));
  expressions.push(require('../nodes/AssignmentExpression'));
  expressions.push(require('../nodes/BinaryExpression'));
  expressions.push(require('../nodes/CallExpression'));
  expressions.push(require('../nodes/ConditionalExpression'));
  expressions.push(require('../nodes/FunctionExpression'));
  expressions.push(require('../nodes/Identifier'));
  expressions.push(require('../nodes/LogicalExpression'));
  expressions.push(require('../nodes/MemberExpression'));
  expressions.push(require('../nodes/NewExpression'));
  expressions.push(require('../nodes/ObjectExpression'));
  expressions.push(require('../nodes/SequenceExpression'));
  expressions.push(require('../nodes/ThisExpression'));
  expressions.push(require('../nodes/UnaryExpression'));
  expressions.push(require('../nodes/UpdateExpression'));
}.call(this);
