// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Identifier, MemberExpression, oneOf;
  Identifier = require('../nodes/Identifier');
  MemberExpression = require('../nodes/MemberExpression');
  oneOf = require('../combinators').oneOf;
  module.exports = oneOf([
    Identifier,
    MemberExpression
  ]);
}.call(this);
