// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Identifier, oneOf;
  Identifier = require('../nodes/Identifier');
  oneOf = require('../combinators').oneOf;
  module.exports = function () {
    return oneOf([Identifier]);
  };
}.call(this);
