// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Identifier, MemberExpression, oneOf;
  Identifier = require('../nodes/Identifier');
  MemberExpression = require('../nodes/MemberExpression');
  oneOf = require('../combinators').oneOf;
  module.exports = function (args) {
    var cache$;
    args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
    return (cache$ = oneOf([
      Identifier,
      MemberExpression
    ])).apply(cache$, [].slice.call(args).concat());
  };
}.call(this);
