// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Boolean_, Null, Number_, oneOf, RegExp_, String_;
  Boolean_ = require('../nodes/Boolean');
  Null = require('../nodes/Null');
  Number_ = require('../nodes/Number');
  RegExp_ = require('../nodes/RegExp');
  String_ = require('../nodes/String');
  oneOf = require('../combinators').oneOf;
  module.exports = function (args) {
    var cache$;
    args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
    return (cache$ = oneOf([
      Boolean_,
      Null,
      Number_,
      RegExp_,
      String_
    ])).apply(cache$, [].slice.call(args).concat());
  };
}.call(this);
