// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var EmptyStatement, oneOf, statements;
  EmptyStatement = require('../nodes/EmptyStatement');
  oneOf = require('../combinators').oneOf;
  statements = [EmptyStatement];
  module.exports = function (depth) {
    var cache$;
    if (!(depth > 0))
      return EmptyStatement(0);
    return (cache$ = oneOf(statements)).apply(cache$, [].slice.call(arguments).concat());
  };
  statements.push(require('../nodes/BlockStatement'));
  statements.push(require('../nodes/BreakStatement'));
  statements.push(require('../nodes/ContinueStatement'));
  statements.push(require('../nodes/DebuggerStatement'));
  statements.push(require('../nodes/DoWhileStatement'));
  statements.push(require('../nodes/EmptyStatement'));
  statements.push(require('../nodes/ExpressionStatement'));
  statements.push(require('../nodes/ForInStatement'));
  statements.push(require('../nodes/ForStatement'));
  statements.push(require('../nodes/FunctionDeclaration'));
  statements.push(require('../nodes/IfStatement'));
  statements.push(require('../nodes/LabeledStatement'));
  statements.push(require('../nodes/ReturnStatement'));
  statements.push(require('../nodes/SwitchStatement'));
  statements.push(require('../nodes/ThrowStatement'));
  statements.push(require('../nodes/TryStatement'));
  statements.push(require('../nodes/VariableDeclaration'));
  statements.push(require('../nodes/WhileStatement'));
  statements.push(require('../nodes/WithStatement'));
}.call(this);
