// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var statements;
  module.exports = statements = [];
  statements.push(require('../nodes/BlockStatement'));
  statements.push(require('../nodes/DebuggerStatement'));
  statements.push(require('../nodes/EmptyStatement'));
  statements.push(require('../nodes/ExpressionStatement'));
  statements.push(require('../nodes/FunctionDeclaration'));
  statements.push(require('../nodes/IfStatement'));
  statements.push(require('../nodes/SwitchStatement'));
  statements.push(require('../nodes/WithStatement'));
}.call(this);
