// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, listOf, listOfExactly, oneOf, randomBool, randomElement;
  cache$ = require('./random');
  randomBool = cache$.randomBool;
  randomElement = cache$.randomElement;
  exports.oneOf = oneOf = function (possibleGenerators) {
    return randomElement(possibleGenerators);
  };
  exports.listOf = listOf = function (possibleGenerators) {
    return function (args) {
      args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
      return function (accum$) {
        var cache$1;
        while (Math.random() < .5) {
          accum$.push((cache$1 = oneOf(possibleGenerators)).apply(cache$1, [].slice.call(args).concat()));
        }
        return accum$;
      }.call(this, []);
    };
  };
  exports.listOfExactly = listOfExactly = function (n, possibleGenerators) {
    return function (args) {
      args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
      return function (accum$) {
        var _, cache$1;
        for (var i$ = 0, length$ = function () {
              var accum$1;
              var accum$1;
              accum$1 = [];
              for (var i$1 = 1; 1 <= n ? i$1 <= n : i$1 >= n; 1 <= n ? ++i$1 : --i$1)
                accum$1.push(i$1);
              return accum$1;
            }.apply(this, arguments).length; i$ < length$; ++i$) {
          _ = function () {
            var accum$1;
            var accum$1;
            accum$1 = [];
            for (var i$1 = 1; 1 <= n ? i$1 <= n : i$1 >= n; 1 <= n ? ++i$1 : --i$1)
              accum$1.push(i$1);
            return accum$1;
          }.apply(this, arguments)[i$];
          accum$.push((cache$1 = oneOf(possibleGenerators)).apply(cache$1, [].slice.call(args).concat()));
        }
        return accum$;
      }.call(this, []);
    };
  };
  exports.listOfAtLeast = function (min, possibleGenerators) {
    return function (args) {
      var cache$1, post, pre;
      args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
      pre = listOfExactly(min, possibleGenerators)();
      post = (cache$1 = listOf(possibleGenerators)).apply(cache$1, [].slice.call(args).concat());
      return [].slice.call(pre).concat([].slice.call(post));
    };
  };
  exports.maybe = function (generator) {
    if (randomBool()) {
      return generator;
    } else {
      return function () {
        return null;
      };
    }
  };
}.call(this);
