// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var randomInt;
  exports.randomInt = randomInt = function (max) {
    return Math.floor(Math.random() * (max + 1));
  };
  exports.randomElement = function (list) {
    return list[randomInt(list.length - 1)];
  };
}.call(this);
