// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var randomInt;
  exports.randomBool = function () {
    return Math.random() < .5;
  };
  exports.randomInt = randomInt = function (max) {
    return Math.floor(Math.random() * (max + 1));
  };
  exports.randomElement = function (list) {
    return list[randomInt(list.length - 1)];
  };
}.call(this);
