// Generated by CoffeeScript 2.0.0-beta5
module.exports = [
  'int',
  'byte',
  'char',
  'goto',
  'long',
  'final',
  'float',
  'short',
  'double',
  'native',
  'throws',
  'boolean',
  'abstract',
  'volatile',
  'transient',
  'synchronized'
];
