// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, listOf, maybe, oneOf;
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  maybe = cache$.maybe;
  listOf = cache$.listOf;
  module.exports = function () {
    return {
      type: 'ArrayExpression',
      elements: listOf([function () {
          return null;
        }].concat([].slice.call(Expression)))
    };
  };
}.call(this);
