// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var ArrayExpression, cache$, construct, Expression, listOf, maybe, Node;
  Node = require('../node');
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  maybe = cache$.maybe;
  listOf = cache$.listOf;
  ArrayExpression = function (super$) {
    extends$(ArrayExpression, super$);
    ArrayExpression.prototype.type = ArrayExpression.name;
    function ArrayExpression(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.elements = listOf([maybe(Expression)])(depth, ancestors);
    }
    return ArrayExpression;
  }(Node);
  module.exports = construct(ArrayExpression);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
