// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var ArrayExpression, cache$, construct, Expression, listOf, maybe;
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  maybe = cache$.maybe;
  listOf = cache$.listOf;
  ArrayExpression = function () {
    ArrayExpression.prototype.type = ArrayExpression.name;
    function ArrayExpression(depth) {
      --depth;
      this.elements = listOf([maybe(Expression)])(depth);
    }
    return ArrayExpression;
  }();
  module.exports = construct(ArrayExpression);
}.call(this);
