// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, oneOf, randomElement;
  Expression = require('../classes/Expression');
  oneOf = require('../combinators').oneOf;
  randomElement = require('../helpers').randomElement;
  module.exports = function () {
    return {
      type: 'BinaryExpression',
      operator: randomElement([
        '==',
        '!=',
        '===',
        '!==',
        '<',
        '<=',
        '>',
        '>=',
        '<<',
        '>>',
        '>>>',
        '+',
        '-',
        '*',
        '/',
        '%',
        '|',
        '^',
        'in',
        'instanceof'
      ]),
      left: oneOf(Expression),
      right: oneOf(Expression)
    };
  };
}.call(this);
