// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var BlockStatement, cache$, construct, listOf, Statement;
  Statement = require('../classes/Statement');
  cache$ = require('../combinators');
  construct = cache$.construct;
  listOf = cache$.listOf;
  BlockStatement = function () {
    BlockStatement.prototype.type = BlockStatement.name;
    BlockStatement.prototype.body = [];
    function BlockStatement(depth) {
      --depth;
      if (depth > 0)
        this.body = listOf([Statement])(depth);
    }
    return BlockStatement;
  }();
  module.exports = construct(BlockStatement);
}.call(this);
