// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var leaf, listOf, Statement, TYPE;
  Statement = require('../classes/Statement');
  listOf = require('../combinators').listOf;
  TYPE = 'BlockStatement';
  leaf = function () {
    return {
      type: TYPE,
      body: []
    };
  };
  module.exports = function (depth) {
    if (!(depth-- > 0))
      return leaf();
    return {
      type: TYPE,
      body: listOf([Statement])(depth)
    };
  };
}.call(this);
