// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var listOf, Statement;
  Statement = require('../classes/Statement');
  listOf = require('../combinators').listOf;
  module.exports = function () {
    return {
      type: 'BlockStatement',
      body: listOf(Statement)
    };
  };
}.call(this);
