// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var oneOf;
  oneOf = require('../combinators').oneOf;
  module.exports = function () {
    return {
      type: 'Literal',
      value: oneOf([
        true,
        false
      ])
    };
  };
}.call(this);
