// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Boolean, construct, randomBool;
  randomBool = require('../random').randomBool;
  construct = require('../combinators').construct;
  Boolean = function () {
    Boolean.prototype.type = 'Literal';
    function Boolean() {
      this.value = randomBool();
    }
    return Boolean;
  }();
  module.exports = construct(Boolean);
}.call(this);
