// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Boolean, Node, randomBool;
  Node = require('../node');
  randomBool = require('../random').randomBool;
  Boolean = function (super$) {
    extends$(Boolean, super$);
    Boolean.prototype.type = 'Literal';
    function Boolean() {
      this.value = randomBool();
    }
    return Boolean;
  }(Node);
  module.exports = function () {
    return new Boolean;
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
