// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Identifier, leaf, maybe, TYPE;
  Identifier = require('./Identifier');
  maybe = require('../combinators').maybe;
  TYPE = 'BreakStatement';
  leaf = function () {
    return {
      type: TYPE,
      label: null
    };
  };
  module.exports = function (depth) {
    if (!(depth-- > 0))
      return leaf();
    return {
      type: TYPE,
      label: maybe(Identifier)(depth)
    };
  };
}.call(this);
