// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, Identifier, leaf, listOf, TYPE;
  Expression = require('../classes/Expression');
  Identifier = require('./Identifier');
  listOf = require('../combinators').listOf;
  TYPE = 'CallExpression';
  leaf = function () {
    return {
      type: TYPE,
      callee: Identifier(0),
      'arguments': []
    };
  };
  module.exports = function (depth) {
    if (!(depth-- > 0))
      return leaf();
    return {
      type: TYPE,
      callee: Expression(depth),
      'arguments': listOf([Expression])(depth)
    };
  };
}.call(this);
