// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, CallExpression, construct, Expression, Identifier, listOf;
  Expression = require('../classes/Expression');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  construct = cache$.construct;
  listOf = cache$.listOf;
  CallExpression = function () {
    CallExpression.prototype.type = CallExpression.name;
    CallExpression.prototype['arguments'] = [];
    function CallExpression(depth) {
      --depth;
      if (depth > 0) {
        this.callee = Expression(depth);
        this['arguments'] = listOf([Expression])(depth);
      } else {
        this.callee = Identifier(0);
      }
    }
    return CallExpression;
  }();
  module.exports = construct(CallExpression);
}.call(this);
