// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var ConditionalExpression, construct, Expression, Node;
  Node = require('../node');
  Expression = require('../classes/Expression');
  construct = require('../combinators').construct;
  ConditionalExpression = function (super$) {
    extends$(ConditionalExpression, super$);
    ConditionalExpression.prototype.type = ConditionalExpression.name;
    function ConditionalExpression(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.test = Expression(depth, ancestors);
      this.consequent = Expression(depth, ancestors);
      this.alternate = Expression(depth, ancestors);
    }
    return ConditionalExpression;
  }(Node);
  module.exports = construct(ConditionalExpression);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
