// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, oneOf;
  Expression = require('../classes/Expression');
  oneOf = require('../combinators').oneOf;
  module.exports = function () {
    return {
      type: 'ConditionalExpression',
      test: oneOf(Expression),
      consequent: oneOf(Expression),
      alternate: oneOf(Expression)
    };
  };
}.call(this);
