// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, TYPE;
  Expression = require('../classes/Expression');
  TYPE = 'ConditionalExpression';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      test: Expression(depth),
      consequent: Expression(depth),
      alternate: Expression(depth)
    };
  };
}.call(this);
