// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Identifier, maybe;
  Identifier = require('./Identifier');
  maybe = require('../combinators').maybe;
  module.exports = function () {
    return {
      type: 'ContinueStatement',
      label: maybe(Identifier)
    };
  };
}.call(this);
