// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, ContinueStatement, Identifier, maybe, Node;
  Node = require('../node');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  construct = cache$.construct;
  maybe = cache$.maybe;
  ContinueStatement = function (super$) {
    extends$(ContinueStatement, super$);
    ContinueStatement.prototype.type = ContinueStatement.name;
    ContinueStatement.prototype.label = null;
    function ContinueStatement(depth) {
      --depth;
      if (depth > 0)
        this.label = maybe(Identifier)(depth);
    }
    return ContinueStatement;
  }(Node);
  module.exports = construct(ContinueStatement);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
