// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var DebuggerStatement, Node;
  Node = require('../node');
  DebuggerStatement = function (super$) {
    extends$(DebuggerStatement, super$);
    function DebuggerStatement() {
      super$.apply(this, arguments);
    }
    DebuggerStatement.prototype.type = DebuggerStatement.name;
    return DebuggerStatement;
  }(Node);
  module.exports = function () {
    return new DebuggerStatement;
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
