// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var DebuggerStatement;
  DebuggerStatement = function () {
    function DebuggerStatement() {
    }
    DebuggerStatement.prototype.type = DebuggerStatement.name;
    return DebuggerStatement;
  }();
  module.exports = function () {
    return new DebuggerStatement;
  };
}.call(this);
