// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, DoWhileStatement, Expression, Node, Statement;
  Node = require('../node');
  Expression = require('../classes/Expression');
  Statement = require('../classes/Statement');
  construct = require('../combinators').construct;
  DoWhileStatement = function (super$) {
    extends$(DoWhileStatement, super$);
    DoWhileStatement.prototype.type = DoWhileStatement.name;
    function DoWhileStatement(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.body = Statement(depth, ancestors);
      this.test = Expression(depth, ancestors);
    }
    return DoWhileStatement;
  }(Node);
  module.exports = construct(DoWhileStatement);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
