// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, Statement, TYPE;
  Expression = require('../classes/Expression');
  Statement = require('../classes/Statement');
  TYPE = 'DoWhileStatement';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      body: Statement(depth),
      test: Expression(depth)
    };
  };
}.call(this);
