// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, DoWhileStatement, Expression, Statement;
  Expression = require('../classes/Expression');
  Statement = require('../classes/Statement');
  construct = require('../combinators').construct;
  DoWhileStatement = function () {
    DoWhileStatement.prototype.type = DoWhileStatement.name;
    function DoWhileStatement(depth) {
      --depth;
      this.body = Statement(depth);
      this.test = Expression(depth);
    }
    return DoWhileStatement;
  }();
  module.exports = construct(DoWhileStatement);
}.call(this);
