// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var EmptyStatement;
  EmptyStatement = function () {
    function EmptyStatement() {
    }
    EmptyStatement.prototype.type = EmptyStatement.name;
    return EmptyStatement;
  }();
  module.exports = function () {
    return new EmptyStatement;
  };
}.call(this);
