// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, ExpressionStatement;
  Expression = require('../classes/Expression');
  construct = require('../combinators').construct;
  ExpressionStatement = function () {
    ExpressionStatement.prototype.type = ExpressionStatement.name;
    function ExpressionStatement(depth) {
      --depth;
      this.expression = Expression(depth);
    }
    return ExpressionStatement;
  }();
  module.exports = construct(ExpressionStatement);
}.call(this);
