// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, TYPE;
  Expression = require('../classes/Expression');
  TYPE = 'ExpressionStatement';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      expression: Expression(depth)
    };
  };
}.call(this);
