// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, oneOf;
  Expression = require('../classes/Expression');
  oneOf = require('../combinators').oneOf;
  module.exports = function () {
    return {
      type: 'ExpressionStatement',
      expression: oneOf(Expression)
    };
  };
}.call(this);
