// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, LHSExpression, oneOf, Statement, TYPE, VariableDeclaration;
  Expression = require('../classes/Expression');
  LHSExpression = require('../classes/LHSExpression');
  Statement = require('../classes/Statement');
  VariableDeclaration = require('./VariableDeclaration');
  oneOf = require('../combinators').oneOf;
  TYPE = 'ForInStatement';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      left: oneOf([LHSExpression])(depth),
      right: Expression(depth),
      body: Statement(depth),
      each: false
    };
  };
}.call(this);
