// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, ForInStatement, LHSExpression, Node, oneOf, Statement, VariableDeclaration;
  Node = require('../node');
  Expression = require('../classes/Expression');
  LHSExpression = require('../classes/LHSExpression');
  Statement = require('../classes/Statement');
  VariableDeclaration = require('./VariableDeclaration');
  cache$ = require('../combinators');
  construct = cache$.construct;
  oneOf = cache$.oneOf;
  ForInStatement = function (super$) {
    extends$(ForInStatement, super$);
    ForInStatement.prototype.type = ForInStatement.name;
    ForInStatement.prototype.each = false;
    function ForInStatement(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.left = LHSExpression(depth, ancestors);
      this.right = Expression(depth, ancestors);
      this.body = Statement(depth, ancestors);
    }
    return ForInStatement;
  }(Node);
  module.exports = construct(ForInStatement);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
