// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, ForInStatement, LHSExpression, oneOf, Statement, VariableDeclaration;
  Expression = require('../classes/Expression');
  LHSExpression = require('../classes/LHSExpression');
  Statement = require('../classes/Statement');
  VariableDeclaration = require('./VariableDeclaration');
  cache$ = require('../combinators');
  construct = cache$.construct;
  oneOf = cache$.oneOf;
  ForInStatement = function () {
    ForInStatement.prototype.type = ForInStatement.name;
    ForInStatement.prototype.each = false;
    function ForInStatement(depth) {
      --depth;
      this.left = LHSExpression(depth);
      this.right = Expression(depth);
      this.body = Statement(depth);
    }
    return ForInStatement;
  }();
  module.exports = construct(ForInStatement);
}.call(this);
