// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, ForStatement, maybe, oneOf, Statement, VariableDeclaration;
  Expression = require('../classes/Expression');
  Statement = require('../classes/Statement');
  VariableDeclaration = require('./VariableDeclaration');
  cache$ = require('../combinators');
  construct = cache$.construct;
  oneOf = cache$.oneOf;
  maybe = cache$.maybe;
  ForStatement = function () {
    ForStatement.prototype.type = ForStatement.name;
    function ForStatement(depth) {
      --depth;
      this.init = maybe(oneOf([
        VariableDeclaration,
        Expression
      ]))(depth);
      this.test = maybe(Expression)(depth);
      this.update = maybe(Expression)(depth);
      this.body = Statement(depth);
    }
    return ForStatement;
  }();
  module.exports = construct(ForStatement);
}.call(this);
