// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var BlockStatement, cache$, Identifier, listOf, maybe, TYPE;
  BlockStatement = require('./BlockStatement');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  listOf = cache$.listOf;
  maybe = cache$.maybe;
  TYPE = 'FunctionExpression';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      id: maybe(Identifier)(depth),
      params: listOf([Identifier])(depth),
      defaults: [],
      rest: null,
      body: BlockStatement(depth),
      generator: false,
      expression: false
    };
  };
}.call(this);
