// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var BlockStatement, Identifier, listOf, TYPE;
  BlockStatement = require('./BlockStatement');
  Identifier = require('./Identifier');
  listOf = require('../combinators').listOf;
  TYPE = 'FunctionDeclaration';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      id: Identifier(depth),
      params: listOf([Identifier])(depth),
      defaults: [],
      rest: null,
      body: BlockStatement(depth),
      generator: false,
      expression: false
    };
  };
}.call(this);
