// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var BlockStatement, cache$, Identifier, listOf, maybe, notReserved;
  BlockStatement = require('./BlockStatement');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  listOf = cache$.listOf;
  maybe = cache$.maybe;
  notReserved = cache$.notReserved;
  module.exports = function () {
    return {
      type: 'FunctionExpression',
      id: maybe(function () {
        return notReserved(Identifier);
      }),
      params: listOf([function () {
          return notReserved(Identifier);
        }], 10),
      defaults: [],
      rest: null,
      body: BlockStatement(),
      generator: false,
      expression: false
    };
  };
}.call(this);
