// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var IdentifierName, RESERVED;
  IdentifierName = require('./IdentifierName');
  RESERVED = require('../reserved');
  module.exports = function () {
    var id;
    id = IdentifierName.apply(null, [].slice.call(arguments).concat());
    id.name = in$(id.name, RESERVED) ? '' + id.name + id.name : id.name;
    return id;
  };
  function in$(member, list) {
    for (var i = 0, length = list.length; i < length; ++i)
      if (i in list && list[i] === member)
        return true;
    return false;
  }
}.call(this);
