// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var identifierPart, identifierStart, randomInt;
  randomInt = require('../helpers').randomInt;
  identifierStart = identifierPart = function () {
    return String.fromCharCode(97 + randomInt(25));
  };
  module.exports = function () {
    return {
      type: 'Identifier',
      name: [identifierStart()].concat([].slice.call(function (accum$) {
        while (Math.random() < .8) {
          accum$.push(identifierPart());
        }
        return accum$;
      }.call(this, []))).join('')
    };
  };
}.call(this);
