// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, identifierPart, identifierStart, problematicNames, randomElement, randomInt, RESERVED, UNRESERVED;
  RESERVED = require('../reserved');
  UNRESERVED = require('../unreserved');
  cache$ = require('../helpers');
  randomInt = cache$.randomInt;
  randomElement = cache$.randomElement;
  identifierStart = identifierPart = function () {
    return String.fromCharCode(97 + randomInt(25));
  };
  problematicNames = [].slice.call(RESERVED).concat([].slice.call(UNRESERVED));
  module.exports = function () {
    if (Math.random() < 1 / 10) {
      return {
        type: 'Identifier',
        name: randomElement(problematicNames)
      };
    } else {
      return {
        type: 'Identifier',
        name: [identifierStart()].concat([].slice.call(function (accum$) {
          while (Math.random() < .8) {
            accum$.push(identifierPart());
          }
          return accum$;
        }.call(this, []))).join('')
      };
    }
  };
}.call(this);
