// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, IfStatement, maybe, Statement;
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  maybe = cache$.maybe;
  IfStatement = function () {
    IfStatement.prototype.type = IfStatement.name;
    function IfStatement(depth) {
      --depth;
      this.test = Expression(depth);
      this.consequent = Statement(depth);
      this.alternate = maybe(Statement)(depth);
    }
    return IfStatement;
  }();
  module.exports = construct(IfStatement);
}.call(this);
