// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, IfStatement, maybe, Node, Statement;
  Node = require('../node');
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  maybe = cache$.maybe;
  IfStatement = function (super$) {
    extends$(IfStatement, super$);
    IfStatement.prototype.type = IfStatement.name;
    function IfStatement(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.test = Expression(depth, ancestors);
      this.consequent = Statement(depth, ancestors);
      this.alternate = maybe(Statement)(depth, ancestors);
    }
    return IfStatement;
  }(Node);
  module.exports = construct(IfStatement);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
