// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, maybe, oneOf, Statement;
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  maybe = cache$.maybe;
  module.exports = function () {
    return {
      type: 'IfStatement',
      test: oneOf(Expression),
      consequent: oneOf(Statement),
      alternate: maybe(function () {
        return oneOf(Statement);
      })
    };
  };
}.call(this);
