// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Identifier, LabeledStatement, Statement;
  Statement = require('../classes/Statement');
  Identifier = require('./Identifier');
  construct = require('../combinators').construct;
  LabeledStatement = function () {
    LabeledStatement.prototype.type = LabeledStatement.name;
    function LabeledStatement(depth) {
      --depth;
      this.label = Identifier(depth);
      this.body = Statement(depth);
    }
    return LabeledStatement;
  }();
  module.exports = construct(LabeledStatement);
}.call(this);
