// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Identifier, notReserved, oneOf, Statement;
  Statement = require('../classes/Statement');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  notReserved = cache$.notReserved;
  module.exports = function () {
    return {
      type: 'LabeledStatement',
      label: notReserved(Identifier),
      body: oneOf(Statement)
    };
  };
}.call(this);
