// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, cache$1, listOf, listOfAtLeast, Null, Number_, oneOf, randomElement, randomInt, String_;
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  listOf = cache$.listOf;
  listOfAtLeast = cache$.listOfAtLeast;
  cache$1 = require('../helpers');
  randomInt = cache$1.randomInt;
  randomElement = cache$1.randomElement;
  Number_ = function () {
    return oneOf([
      function () {
        return {
          type: 'Literal',
          value: 0
        };
      },
      function () {
        return {
          type: 'Literal',
          value: 0,
          raw: '0.'
        };
      },
      function () {
        return {
          type: 'Literal',
          value: 0,
          raw: '.0'
        };
      },
      function () {
        var int;
        int = randomInt(Math.pow(2, 53) - 1);
        return {
          type: 'Literal',
          value: int
        };
      }
    ]);
  };
  String_ = function () {
    var chars;
    chars = function (accum$) {
      while (Math.random() < .95) {
        accum$.push(String.fromCharCode(32 + randomInt(94)));
      }
      return accum$;
    }.call(this, []);
    return {
      type: 'Literal',
      value: chars.join('')
    };
  };
  Null = function () {
    return {
      type: 'Literal',
      value: null
    };
  };
  module.exports = function () {
    return oneOf([
      Number_,
      String_,
      Null
    ]);
  };
}.call(this);
