// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, LogicalExpression, OPERATORS, randomElement;
  Expression = require('../classes/Expression');
  randomElement = require('../random').randomElement;
  construct = require('../combinators').construct;
  OPERATORS = [
    '||',
    '&&'
  ];
  LogicalExpression = function () {
    LogicalExpression.prototype.type = LogicalExpression.name;
    function LogicalExpression(depth) {
      --depth;
      this.operator = randomElement(OPERATORS);
      this.left = Expression(depth);
      this.right = Expression(depth);
    }
    return LogicalExpression;
  }();
  module.exports = construct(LogicalExpression);
}.call(this);
