// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, oneOf, OPERATORS, TYPE;
  Expression = require('../classes/Expression');
  oneOf = require('../combinators').oneOf;
  OPERATORS = [
    '||',
    '&&'
  ];
  TYPE = 'LogicalExpression';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      operator: oneOf(OPERATORS),
      left: Expression(depth),
      right: Expression(depth)
    };
  };
}.call(this);
