// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var DynamicMemberExpression, Expression, IdentifierName, oneOf, StaticMemberExpression;
  Expression = require('../classes/Expression');
  IdentifierName = require('./IdentifierName');
  oneOf = require('../combinators').oneOf;
  DynamicMemberExpression = function () {
    return {
      type: 'MemberExpression',
      object: oneOf(Expression),
      property: oneOf(Expression),
      computed: true
    };
  };
  StaticMemberExpression = function () {
    return {
      type: 'MemberExpression',
      object: oneOf(Expression),
      property: IdentifierName(),
      computed: false
    };
  };
  module.exports = function () {
    return oneOf([
      DynamicMemberExpression,
      StaticMemberExpression
    ]);
  };
}.call(this);
