// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var DynamicMemberExpression, Expression, IdentifierName, oneOf, StaticMemberExpression, TYPE;
  Expression = require('../classes/Expression');
  IdentifierName = require('./IdentifierName');
  oneOf = require('../combinators').oneOf;
  TYPE = 'MemberExpression';
  DynamicMemberExpression = function (depth) {
    return {
      type: TYPE,
      object: Expression(depth),
      property: Expression(depth),
      computed: true
    };
  };
  StaticMemberExpression = function (depth) {
    return {
      type: TYPE,
      object: Expression(depth),
      property: IdentifierName(depth),
      computed: false
    };
  };
  module.exports = function (depth) {
    --depth;
    return oneOf([
      DynamicMemberExpression,
      StaticMemberExpression
    ])(depth);
  };
}.call(this);
