// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, Identifier, listOf, NewExpression;
  Expression = require('../classes/Expression');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  construct = cache$.construct;
  listOf = cache$.listOf;
  NewExpression = function () {
    NewExpression.prototype.type = NewExpression.name;
    NewExpression.prototype['arguments'] = [];
    function NewExpression(depth) {
      --depth;
      if (depth > 0) {
        this.callee = Expression(depth);
        this['arguments'] = listOf([Expression])(depth);
      } else {
        this.callee = Identifier(0);
      }
    }
    return NewExpression;
  }();
  module.exports = construct(NewExpression);
}.call(this);
