// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, listOf, oneOf;
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  listOf = cache$.listOf;
  module.exports = function () {
    return {
      type: 'NewExpression',
      callee: oneOf(Expression),
      'arguments': listOf(Expression)
    };
  };
}.call(this);
