// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Node, Null;
  Node = require('../node');
  Null = function (super$) {
    extends$(Null, super$);
    function Null() {
      super$.apply(this, arguments);
    }
    Null.prototype.type = 'Literal';
    Null.prototype.value = null;
    return Null;
  }(Node);
  module.exports = function () {
    return new Null;
  };
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
