// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Null;
  Null = function () {
    function Null() {
    }
    Null.prototype.type = 'Literal';
    Null.prototype.value = null;
    return Null;
  }();
  module.exports = function () {
    return new Null;
  };
}.call(this);
