// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, IdentifierName, Key, leaf, listOf, Number_, oneOf, Property, String_, TYPE;
  Expression = require('../classes/Expression');
  IdentifierName = require('./IdentifierName');
  Number_ = require('./Number');
  String_ = require('./String');
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  listOf = cache$.listOf;
  TYPE = 'ObjectExpression';
  leaf = function (depth) {
    return {
      type: TYPE,
      properties: []
    };
  };
  Key = function (args) {
    var cache$1;
    args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
    return (cache$1 = oneOf([
      String_,
      Number_,
      IdentifierName
    ])).apply(cache$1, [].slice.call(args).concat());
  };
  Property = function (depth) {
    return {
      kind: 'init',
      key: Key(depth),
      value: Expression(depth)
    };
  };
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      properties: listOf([Property])(depth)
    };
  };
}.call(this);
