// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, listOfAtLeast, Program, Statement;
  Statement = require('../classes/Statement');
  cache$ = require('../combinators');
  construct = cache$.construct;
  listOfAtLeast = cache$.listOfAtLeast;
  Program = function () {
    Program.prototype.type = Program.name;
    Program.prototype.body = [];
    function Program(depth) {
      --depth;
      if (depth > 0)
        this.body = listOfAtLeast(1, [Statement])(depth);
    }
    return Program;
  }();
  module.exports = construct(Program);
}.call(this);
