// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var leaf, listOfAtLeast, Statement, TYPE;
  Statement = require('../classes/Statement');
  listOfAtLeast = require('../combinators').listOfAtLeast;
  TYPE = 'Program';
  leaf = function () {
    return {
      type: TYPE,
      body: []
    };
  };
  module.exports = function (depth) {
    if (!(depth-- > 0))
      return leaf();
    return {
      type: TYPE,
      body: listOfAtLeast(1, [Statement])(depth)
    };
  };
}.call(this);
