// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Alternation, Boundary, cache$, Character, CharacterClass, CharacterClassCharacter, CharacterClassRange, charVal, genSafeRegExp, Grouping, Hex, listOf, listOfExactly, oneOf, printableAscii, randomInt, RegExpSource, Repetition, Sequence, TYPE;
  cache$ = require('../combinators');
  oneOf = cache$.oneOf;
  listOf = cache$.listOf;
  listOfExactly = cache$.listOfExactly;
  randomInt = require('../random').randomInt;
  TYPE = 'Literal';
  printableAscii = function () {
    return String.fromCharCode(32 + randomInt(94));
  };
  charVal = function (str) {
    if (str[0] === '\\') {
      switch (str[1]) {
      case 'u':
      case 'x':
        return parseInt(str.slice(2), 16);
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
        return parseInt(str.slice(1), 8);
      case 'b':
        return 8;
      case 't':
        return 9;
      case 'n':
        return 10;
      case 'v':
        return 11;
      case 'f':
        return 12;
      case 'r':
        return 13;
      default:
        return str.charCodeAt(1);
      }
    } else {
      return str.charCodeAt(0);
    }
  };
  Alternation = function (depth) {
    if (!depth--)
      return '';
    return listOf([
      Grouping,
      CharacterClass,
      Repetition,
      Sequence
    ])(depth).join('|');
  };
  Hex = function () {
    var chars;
    chars = '0123456789abcdefABCDEF'.split('');
    return function () {
      return oneOf(chars);
    };
  }();
  Character = function () {
    return oneOf([
      function () {
        var ch;
        while (true) {
          ch = printableAscii();
          if (!in$(ch, [
              '[',
              '(',
              ')',
              '{',
              '?',
              '*',
              '+',
              '|',
              '\\',
              '$',
              '^'
            ]))
            return ch;
        }
      },
      function () {
        return '\\u' + listOfExactly(4, [Hex])().join('');
      },
      function () {
        return '\\x' + listOfExactly(2, [Hex])().join('');
      },
      function () {
        var ch;
        while (true) {
          ch = printableAscii();
          if (!in$(ch, [
              'u',
              'x',
              'b',
              'B',
              'c',
              '1',
              '2',
              '3',
              '4',
              '5',
              '6',
              '7',
              '8',
              '9'
            ]))
            return '\\' + ch;
        }
      }
    ])();
  };
  Boundary = function () {
    return oneOf([
      '^',
      '$',
      '\\b'
    ]);
  };
  CharacterClassCharacter = function () {
    var ch;
    ch = '-';
    while (ch === '-' || ch === ']') {
      ch = oneOf([
        Character,
        function () {
          return oneOf([
            '[',
            '(',
            ')',
            '{',
            '?',
            '*',
            '+',
            '|',
            '$'
          ]);
        }
      ])();
    }
    return ch;
  };
  CharacterClassRange = function () {
    var a, b, cache$1, left, right;
    a = CharacterClassCharacter();
    b = CharacterClassCharacter();
    cache$1 = charVal(a) < charVal(b) ? [
      a,
      b
    ] : [
      b,
      a
    ];
    left = cache$1[0];
    right = cache$1[1];
    return '' + left + '-' + right;
  };
  CharacterClass = function (depth) {
    var source;
    if (!depth--)
      return '[]';
    source = listOf([
      CharacterClassCharacter,
      CharacterClassRange
    ])().join('');
    source = source.replace(/\\$/g, '\\a');
    return '[' + oneOf([
      '^',
      '-',
      ''
    ]) + source + oneOf([
      '-',
      ''
    ]) + ']';
  };
  Grouping = function (depth) {
    if (!depth--)
      return '()';
    return '(' + oneOf([
      '?:',
      '?!',
      '?=',
      ''
    ]) + RegExpSource(depth) + ')';
  };
  Repetition = function (depth) {
    if (!depth--)
      return '';
    return '' + oneOf([
      Grouping,
      CharacterClass,
      Character
    ])(depth) + oneOf([
      '?',
      '+',
      '*',
      '*?',
      '+?'
    ]);
  };
  Sequence = function () {
    return listOf([
      Character,
      Boundary
    ])().join('');
  };
  RegExpSource = function (depth) {
    if (!depth--)
      return '';
    return oneOf([
      Alternation,
      Grouping,
      CharacterClass,
      Repetition,
      Sequence
    ])(depth);
  };
  genSafeRegExp = function () {
    var e, source;
    try {
      source = RegExpSource(6);
      return new RegExp(source);
    } catch (e$) {
      e = e$;
      console.dir(source);
      return genSafeRegExp();
    }
  };
  module.exports = function () {
    return {
      type: TYPE,
      value: genSafeRegExp()
    };
  };
  function in$(member, list) {
    for (var i = 0, length = list.length; i < length; ++i)
      if (i in list && list[i] === member)
        return true;
    return false;
  }
}.call(this);
