// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, maybe, oneOf, TYPE;
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  maybe = cache$.maybe;
  oneOf = cache$.oneOf;
  TYPE = 'ReturnStatement';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      argument: maybe(Expression)(depth)
    };
  };
}.call(this);
