// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, maybe, oneOf;
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  maybe = cache$.maybe;
  oneOf = cache$.oneOf;
  module.exports = function () {
    return {
      type: 'ReturnStatement',
      argument: maybe(function () {
        return oneOf(Expression);
      })
    };
  };
}.call(this);
