// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, listOfAtLeast, TYPE;
  Expression = require('../classes/Expression');
  listOfAtLeast = require('../combinators').listOfAtLeast;
  TYPE = 'SequenceExpression';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      expressions: listOfAtLeast(2, [Expression])(depth)
    };
  };
}.call(this);
