// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, listOfAtLeast, SequenceExpression;
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  listOfAtLeast = cache$.listOfAtLeast;
  SequenceExpression = function () {
    SequenceExpression.prototype.type = SequenceExpression.name;
    function SequenceExpression(depth) {
      --depth;
      this.expressions = listOfAtLeast(2, [Expression])(depth);
    }
    return SequenceExpression;
  }();
  module.exports = construct(SequenceExpression);
}.call(this);
