// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, listOfAtLeast, Node, SequenceExpression;
  Node = require('../node');
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  listOfAtLeast = cache$.listOfAtLeast;
  SequenceExpression = function (super$) {
    extends$(SequenceExpression, super$);
    SequenceExpression.prototype.type = SequenceExpression.name;
    function SequenceExpression(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.expressions = listOfAtLeast(2, [Expression])(depth, ancestors);
    }
    return SequenceExpression;
  }(Node);
  module.exports = construct(SequenceExpression);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
