// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var randomInt, String_;
  randomInt = require('../random').randomInt;
  String_ = function () {
    String_.prototype.type = 'Literal';
    function String_() {
      this.value = function (accum$) {
        while (Math.random() < .9) {
          accum$.push(String.fromCharCode(32 + randomInt(94)));
        }
        return accum$;
      }.call(this, []).join('');
    }
    return String_;
  }();
  module.exports = function () {
    return new String_;
  };
}.call(this);
