// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var randomInt, TYPE;
  randomInt = require('../helpers').randomInt;
  TYPE = 'Literal';
  module.exports = function () {
    var chars;
    chars = function (accum$) {
      while (Math.random() < .9) {
        accum$.push(String.fromCharCode(32 + randomInt(94)));
      }
      return accum$;
    }.call(this, []);
    return {
      type: TYPE,
      value: chars.join('')
    };
  };
}.call(this);
