// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, listOf, listOfAtLeast, oneOf, Statement, SwitchCase, SwitchCaseDefault, SwitchStatement;
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  cache$ = require('../combinators');
  construct = cache$.construct;
  oneOf = cache$.oneOf;
  listOf = cache$.listOf;
  listOfAtLeast = cache$.listOfAtLeast;
  SwitchCase = function () {
    SwitchCase.prototype.type = 'SwitchCase';
    function SwitchCase(depth) {
      this.test = Expression(depth);
      this.consequent = listOfAtLeast(1, [Statement])(depth);
    }
    return SwitchCase;
  }();
  SwitchCaseDefault = function () {
    SwitchCaseDefault.prototype.type = 'SwitchCase';
    SwitchCaseDefault.prototype.test = null;
    function SwitchCaseDefault(depth) {
      this.consequent = listOfAtLeast(1, [Statement])(depth);
    }
    return SwitchCaseDefault;
  }();
  SwitchStatement = function () {
    SwitchStatement.prototype.type = SwitchStatement.name;
    SwitchStatement.prototype.cases = [];
    SwitchStatement.prototype.lexical = false;
    function SwitchStatement(depth) {
      --depth;
      if (depth > 0) {
        this.discriminant = Expression(depth);
        this.cases = listOf([construct(SwitchCase)])(depth).concat(oneOf([
          construct(SwitchCaseDefault),
          function () {
            return [];
          }
        ])(depth));
      } else {
        this.discriminant = Expression(0);
      }
    }
    return SwitchStatement;
  }();
  module.exports = construct(SwitchStatement);
}.call(this);
