// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, ThisExpression;
  construct = require('../combinators').construct;
  ThisExpression = function () {
    function ThisExpression() {
    }
    ThisExpression.prototype.type = ThisExpression.name;
    return ThisExpression;
  }();
  module.exports = construct(ThisExpression);
}.call(this);
