// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Node, ThisExpression;
  Node = require('../node');
  construct = require('../combinators').construct;
  ThisExpression = function (super$) {
    extends$(ThisExpression, super$);
    function ThisExpression() {
      super$.apply(this, arguments);
    }
    ThisExpression.prototype.type = ThisExpression.name;
    return ThisExpression;
  }(Node);
  module.exports = construct(ThisExpression);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
