// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, ThrowStatement;
  Expression = require('../classes/Expression');
  construct = require('../combinators').construct;
  ThrowStatement = function () {
    ThrowStatement.prototype.type = ThrowStatement.name;
    function ThrowStatement(depth) {
      --depth;
      this.argument = Expression(depth);
    }
    return ThrowStatement;
  }();
  module.exports = construct(ThrowStatement);
}.call(this);
