// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, OPERATORS, randomElement, UnaryExpression;
  Expression = require('../classes/Expression');
  construct = require('../combinators').construct;
  randomElement = require('../random').randomElement;
  OPERATORS = [
    '-',
    '+',
    '!',
    '~',
    'typeof',
    'void',
    'delete'
  ];
  UnaryExpression = function () {
    UnaryExpression.prototype.type = UnaryExpression.name;
    UnaryExpression.prototype.prefix = true;
    function UnaryExpression(depth) {
      --depth;
      this.operator = randomElement(OPERATORS);
      this.argument = Expression(depth);
    }
    return UnaryExpression;
  }();
  module.exports = construct(UnaryExpression);
}.call(this);
