// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, oneOf, OPERATORS, TYPE;
  Expression = require('../classes/Expression');
  oneOf = require('../combinators').oneOf;
  OPERATORS = [
    '-',
    '+',
    '!',
    '~',
    'typeof',
    'void',
    'delete'
  ];
  TYPE = 'UnaryExpression';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      operator: oneOf(OPERATORS),
      prefix: true,
      argument: Expression(depth)
    };
  };
}.call(this);
