// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var LHSExpression, oneOf, randomBool, TYPE;
  LHSExpression = require('../classes/LHSExpression');
  oneOf = require('../combinators').oneOf;
  randomBool = require('../helpers').randomBool;
  TYPE = 'UpdateExpression';
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      operator: oneOf([
        '++',
        '--'
      ]),
      argument: LHSExpression(depth),
      prefix: randomBool()
    };
  };
}.call(this);
