// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, LHSExpression, OPERATORS, randomBool, randomElement, UpdateExpression;
  LHSExpression = require('../classes/LHSExpression');
  construct = require('../combinators').construct;
  cache$ = require('../random');
  randomBool = cache$.randomBool;
  randomElement = cache$.randomElement;
  OPERATORS = [
    '++',
    '--'
  ];
  UpdateExpression = function () {
    UpdateExpression.prototype.type = UpdateExpression.name;
    function UpdateExpression(depth) {
      --depth;
      this.operator = randomElement(OPERATORS);
      this.argument = LHSExpression(depth);
      this.prefix = randomBool();
    }
    return UpdateExpression;
  }();
  module.exports = construct(UpdateExpression);
}.call(this);
