// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, construct, Expression, Identifier, listOfAtLeast, maybe, VariableDeclaration, VariableDeclarator;
  Expression = require('../classes/Expression');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  construct = cache$.construct;
  maybe = cache$.maybe;
  listOfAtLeast = cache$.listOfAtLeast;
  VariableDeclarator = function () {
    VariableDeclarator.prototype.type = VariableDeclarator.name;
    function VariableDeclarator(depth) {
      this.id = Identifier(depth);
      this.init = maybe(Expression)(depth);
    }
    return VariableDeclarator;
  }();
  VariableDeclaration = function () {
    VariableDeclaration.prototype.type = VariableDeclaration.name;
    function VariableDeclaration(depth) {
      --depth;
      this.declarations = listOfAtLeast(1, [construct(VariableDeclarator)])(depth);
      this.kind = 'var';
    }
    return VariableDeclaration;
  }();
  module.exports = construct(VariableDeclaration);
}.call(this);
