// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var cache$, Expression, Identifier, listOfAtLeast, maybe, TYPE, VariableDeclarator;
  Expression = require('../classes/Expression');
  Identifier = require('./Identifier');
  cache$ = require('../combinators');
  maybe = cache$.maybe;
  listOfAtLeast = cache$.listOfAtLeast;
  TYPE = 'VariableDeclaration';
  VariableDeclarator = function (depth) {
    return {
      type: 'VariableDeclarator',
      id: Identifier(depth),
      init: maybe(Expression)(depth)
    };
  };
  module.exports = function (depth) {
    --depth;
    return {
      type: TYPE,
      declarations: listOfAtLeast(1, [VariableDeclarator])(depth),
      kind: 'var'
    };
  };
}.call(this);
