// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, Statement, WhileStatement;
  Expression = require('../classes/Expression');
  Statement = require('../classes/Statement');
  construct = require('../combinators').construct;
  WhileStatement = function () {
    WhileStatement.prototype.type = WhileStatement.name;
    function WhileStatement(depth) {
      --depth;
      this.test = Expression(depth);
      this.body = Statement(depth);
    }
    return WhileStatement;
  }();
  module.exports = construct(WhileStatement);
}.call(this);
