// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var Expression, oneOf, Statement;
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  oneOf = require('../combinators').oneOf;
  module.exports = function () {
    return {
      type: 'WithStatement',
      object: oneOf(Expression),
      body: oneOf(Statement)
    };
  };
}.call(this);
