// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, Statement, WithStatement;
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  construct = require('../combinators').construct;
  WithStatement = function () {
    WithStatement.prototype.type = WithStatement.name;
    function WithStatement(depth) {
      --depth;
      this.object = Expression(depth);
      this.body = Statement(depth);
    }
    return WithStatement;
  }();
  module.exports = construct(WithStatement);
}.call(this);
