// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var construct, Expression, Node, Statement, WithStatement;
  Node = require('../node');
  Statement = require('../classes/Statement');
  Expression = require('../classes/Expression');
  construct = require('../combinators').construct;
  WithStatement = function (super$) {
    extends$(WithStatement, super$);
    WithStatement.prototype.type = WithStatement.name;
    function WithStatement(depth, ancestors) {
      --depth;
      ancestors = [this].concat(ancestors);
      this.object = Expression(depth, ancestors);
      this.body = Statement(depth, ancestors);
    }
    return WithStatement;
  }(Node);
  module.exports = construct(WithStatement);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
  function extends$(child, parent) {
    for (var key in parent)
      if (isOwn$(parent, key))
        child[key] = parent[key];
    function ctor() {
      this.constructor = child;
    }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor;
    child.__super__ = parent.prototype;
    return child;
  }
}.call(this);
